const {chromium}=require('playwright');
(async()=>{ const b=await chromium.launch(); const p=await b.newPage({viewport:{width:390,height:844},deviceScaleFactor:2}); const errs=[]; p.on('pageerror',e=>errs.push(e.message));
 await p.addInitScript(()=>{ sessionStorage.setItem('obSnd','0'); });
 await p.goto('http://localhost:8812/myeongri.html'); await p.waitForTimeout(3500);
 await p.screenshot({path:'cc_1room.png'});
 await p.evaluate(()=>{ document.getElementById('enterBtn').click(); grindInk=async()=>{}; document.getElementById('nm').value='은주'; }); await p.waitForTimeout(2200);
 await p.screenshot({path:'cc_2form.png'});
 await p.evaluate(()=>{ const s=document.getElementById('sIntro'); s.scrollTop=420; }); await p.waitForTimeout(600);
 await p.screenshot({path:'cc_3formscroll.png'});
 await p.click('#intake .tp button[data-k="job"]'); await p.click('#intake .st button[data-k="emp"]');
 await p.evaluate(()=>{ const s=document.getElementById('sIntro'); s.scrollTop=s.scrollHeight; }); await p.waitForTimeout(300);
 await p.screenshot({path:'cc_4formbottom.png'});
 await p.evaluate(()=>document.getElementById('goBtn').click()); await p.waitForTimeout(15000);
 await p.screenshot({path:'cc_5hero.png'});
 await p.evaluate(()=>{ const r=document.getElementById('sRep'), f=document.querySelector('.frd'); r.scrollTop=f.offsetTop-40; }); await p.waitForTimeout(800);
 await p.screenshot({path:'cc_6seal.png'});
 await p.evaluate(()=>{ const r=document.getElementById('sRep'), f=document.getElementById('dLock'); r.scrollTop=f.offsetTop-60; }); await p.waitForTimeout(500);
 await p.screenshot({path:'cc_7lock.png'});
 const v=await p.evaluate(()=>[...document.querySelectorAll('video')].map(v=>v.getAttribute('controlslist')).filter(Boolean).length+'/'+document.querySelectorAll('video').length);
 console.log(errs, v); await b.close(); })();
